title: Pratik Katke
logo: /assets/img/logo.png
description: 
I am working as a Data Scientist, my role description is to alise with business stakeholders, understand their requirement trying to resolve business problem with proper data reporting, dashboard creation and report building.

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
